"""Default persona

Revision ID: 132abfcf74a4
Revises: 77b123a0b59b
Create Date: 2025-08-04 12:59:25.573982

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "132abfcf74a4"
down_revision = "77b123a0b59b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("actor", sa.Column("default_persona", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "actor", ["liked"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "actor", type_="unique")
    op.drop_column("actor", "default_persona")
    # ### end Alembic commands ###
