"""Actor Media cascade

Revision ID: 448402a387da
Revises: 4f1992763967
Create Date: 2025-09-27 20:08:49.630748

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "448402a387da"
down_revision = "4f1992763967"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
