"""Products and payments

Revision ID: 4f1992763967
Revises: 132abfcf74a4
Create Date: 2025-09-23 07:08:35.072791

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import LocaleType, CurrencyType, CountryType

# revision identifiers, used by Alembic.
revision = "4f1992763967"
down_revision = "132abfcf74a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openwallet",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("publicName", sa.String(), nullable=True),
        sa.Column("assetCode", CurrencyType(length=3), nullable=False),
        sa.Column("assetScale", sa.Integer(), nullable=False),
        sa.Column("authServer", sa.String(), nullable=True),
        sa.Column("resourceServer", sa.String(), nullable=True),
        sa.Column("keyID", sa.String(), nullable=True),
        sa.Column("privateKey", sa.String(), nullable=True),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("privateKey"),
    )
    op.create_index(op.f("ix_openwallet_address"), "openwallet", ["address"], unique=False)
    op.create_index(op.f("ix_openwallet_id"), "openwallet", ["id"], unique=False)
    op.create_table(
        "product",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "OneTime", "Subscription", "Conditional", "ConditionalSubscription", checkfirst=True, name="producttype"
            ),
            nullable=False,
        ),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.Column("editor_id", sa.String(length=26), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "condition", postgresql.ENUM("Amount", "Release", checkfirst=True, name="conditiontype"), nullable=True
        ),
        sa.Column("condition_total", sa.Float(), nullable=True),
        sa.Column(
            "renewal",
            postgresql.ENUM("Weekly", "Monthly", "Annually", "Conditionally", checkfirst=True, name="renewaltype"),
            nullable=True,
        ),
        sa.Column("renewal_periods", sa.Integer(), nullable=True),
        sa.Column("allowed_countries", postgresql.ARRAY(CountryType(length=2)), nullable=True),
        sa.Column("blocked_countries", postgresql.ARRAY(CountryType(length=2)), nullable=True),
        sa.Column("currency", CurrencyType(length=3), nullable=True),
        sa.Column(
            "fees",
            postgresql.ENUM("Buyer", "Seller", "Choice", checkfirst=True, name="productfeeresponsibilitytype"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    op.create_table(
        "asset",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column(
            "type", postgresql.ENUM("Download", "Image", checkfirst=True, name="productassettype"), nullable=False
        ),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_asset_id"), "asset", ["id"], unique=False)
    op.create_table(
        "contributor",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM(
                "Creator",
                "Editor",
                "Translator",
                "Illustrator",
                "Curator",
                checkfirst=True,
                name="productcontributorroletype",
            ),
            nullable=False,
        ),
        sa.Column("ratio", sa.Float(), nullable=True),
        sa.Column("limit_value", sa.Float(), nullable=True),
        sa.Column("limit_currency", CurrencyType(length=3), nullable=True),
        sa.Column("limit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("countries", postgresql.ARRAY(CountryType(length=2)), nullable=True),
        sa.Column("product_id", sa.String(length=26), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contributor_id"), "contributor", ["id"], unique=False)
    op.create_table(
        "price",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("amount", sa.String(), nullable=False),
        sa.Column("currency", CurrencyType(length=3), nullable=False),
        sa.Column("scale", sa.Integer(), nullable=False),
        sa.Column("countries", postgresql.ARRAY(CountryType(length=2)), nullable=True),
        sa.Column(
            "fees",
            postgresql.ENUM("Buyer", "Seller", "Choice", checkfirst=True, name="productfeeresponsibilitytype"),
            nullable=True,
        ),
        sa.Column("product_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_id"), "price", ["id"], unique=False)
    op.create_table(
        "productdescription",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("product_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_productdescription_id"), "productdescription", ["id"], unique=False)
    op.create_table(
        "productname",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("product_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_productname_id"), "productname", ["id"], unique=False)
    op.create_table(
        "contributorterms",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("contributor_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("terms", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["contributor_id"], ["contributor.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contributorterms_id"), "contributorterms", ["id"], unique=False)
    op.create_table(
        "openorder",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("product_id", sa.String(length=26), nullable=False),
        sa.Column("price_id", sa.String(length=26), nullable=False),
        sa.Column("country", CountryType(length=2), nullable=False),
        sa.Column(
            "renewal",
            postgresql.ENUM("Weekly", "Monthly", "Annually", "Conditionally", checkfirst=True, name="renewaltype"),
            nullable=True,
        ),
        sa.Column("renewal_periods", sa.Integer(), nullable=True),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column(
            "fees",
            postgresql.ENUM("Buyer", "Seller", "Choice", checkfirst=True, name="productfeeresponsibilitytype"),
            nullable=True,
        ),
        sa.Column("buyer_id", sa.String(length=26), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("incoming_payments", postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
        sa.Column("incoming_quotes", postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
        sa.Column("interactive_outgoings", postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["openwallet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["price.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_openorder_id"), "openorder", ["id"], unique=False)
    op.create_table(
        "openreceipt",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("product_id", sa.String(length=26), nullable=False),
        sa.Column("price_id", sa.String(length=26), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "OneTime", "Subscription", "Conditional", "ConditionalSubscription", checkfirst=True, name="producttype"
            ),
            nullable=False,
        ),
        sa.Column("country", CountryType(length=2), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "fees",
            postgresql.ENUM("Buyer", "Seller", "Choice", checkfirst=True, name="productfeeresponsibilitytype"),
            nullable=True,
        ),
        sa.Column("buyer_id", sa.String(length=26), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("order_id", sa.String(length=26), nullable=False),
        sa.Column("amount", sa.String(), nullable=False),
        sa.Column("assetCode", CurrencyType(length=3), nullable=False),
        sa.Column("assetScale", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["openwallet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["openorder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["price.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_openreceipt_id"), "openreceipt", ["id"], unique=False)
    op.create_table(
        "openrecipient",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("wallet_id", sa.String(length=26), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("product_id", sa.String(length=26), nullable=False),
        sa.Column("price_id", sa.String(length=26), nullable=False),
        sa.Column("receipt_id", sa.String(length=26), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("assetCode", CurrencyType(length=3), nullable=False),
        sa.Column("assetScale", sa.Integer(), nullable=False),
        sa.Column("payment_response", postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["price.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["openreceipt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["openwallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_openrecipient_id"), "openrecipient", ["id"], unique=False)
    op.drop_constraint(op.f("actor_creator_id_fkey"), "actor", type_="foreignkey")
    op.create_foreign_key(None, "actor", "creator", ["creator_id"], ["id"])
    op.drop_constraint(op.f("actor_tag_actor_id_fkey"), "actor_tag", type_="foreignkey")
    op.create_foreign_key(None, "actor_tag", "actor", ["actor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "actor_tag", type_="foreignkey")
    op.create_foreign_key(
        op.f("actor_tag_actor_id_fkey"), "actor_tag", "actor", ["actor_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "actor", type_="foreignkey")
    op.create_foreign_key(op.f("actor_creator_id_fkey"), "actor", "creator", ["creator_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("ix_openrecipient_id"), table_name="openrecipient")
    op.drop_table("openrecipient")
    op.drop_index(op.f("ix_openreceipt_id"), table_name="openreceipt")
    op.drop_table("openreceipt")
    op.drop_index(op.f("ix_openorder_id"), table_name="openorder")
    op.drop_table("openorder")
    op.drop_index(op.f("ix_contributorterms_id"), table_name="contributorterms")
    op.drop_table("contributorterms")
    op.drop_index(op.f("ix_productname_id"), table_name="productname")
    op.drop_table("productname")
    op.drop_index(op.f("ix_productdescription_id"), table_name="productdescription")
    op.drop_table("productdescription")
    op.drop_index(op.f("ix_price_id"), table_name="price")
    op.drop_table("price")
    op.drop_index(op.f("ix_contributor_id"), table_name="contributor")
    op.drop_table("contributor")
    op.drop_index(op.f("ix_asset_id"), table_name="asset")
    op.drop_table("asset")
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_openwallet_id"), table_name="openwallet")
    op.drop_index(op.f("ix_openwallet_address"), table_name="openwallet")
    op.drop_table("openwallet")
    # ### end Alembic commands ###
