"""Actor maker-to-work relationship

Revision ID: 598b46663ceb
Revises: 448402a387da
Create Date: 2025-10-20 08:15:25.560578

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "598b46663ceb"
down_revision = "448402a387da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("actor", sa.Column("maker_id", sa.String(length=26), nullable=True))
    op.create_foreign_key(None, "actor", "actor", ["maker_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "actor", type_="foreignkey")
    op.drop_column("actor", "maker_id")
    # ### end Alembic commands ###
