"""ActivityPub definitions

Revision ID: 77b123a0b59b
Revises: 8bdea1b48f5d
Create Date: 2025-06-06 21:10:30.067487

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import TSVectorType, LocaleType

# revision identifiers, used by Alembic.
revision = "77b123a0b59b"
down_revision = "8bdea1b48f5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediaattachment",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("URL", sa.String(), nullable=True),
        sa.Column("remoteURL", sa.String(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "Image",
                "Audio",
                "Video",
                "Gifv",
                "Unknown",
                name="mediatype",
                checkfirst=True,
            ),
            nullable=True,
        ),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("thumbnail", sa.Boolean(), nullable=True),
        sa.Column("as_avatar", sa.Boolean(), nullable=True),
        sa.Column("as_standout", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_mediaattachment_id"), "mediaattachment", ["id"], unique=False)
    op.create_table(
        "move",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("attempted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("succeeded", sa.DateTime(timezone=True), nullable=True),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("originURI", sa.String(), nullable=False),
        sa.Column("targetURI", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_move_URI"), "move", ["URI"], unique=True)
    op.create_index(op.f("ix_move_id"), "move", ["id"], unique=False)
    op.create_index(op.f("ix_move_originURI"), "move", ["originURI"], unique=True)
    op.create_index(op.f("ix_move_targetURI"), "move", ["targetURI"], unique=True)
    op.create_table(
        "rule",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rule_id"), "rule", ["id"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "name_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"name\")", persisted=True),
            nullable=True,
        ),
        sa.Column("local", sa.Boolean(), nullable=True),
        sa.Column("usable", sa.Boolean(), nullable=True),
        sa.Column("listable", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_id"), "tag", ["id"], unique=False)
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    op.create_index("ix_tag_name_vector", "tag", ["name_vector"], unique=False, postgresql_using="gin")
    op.create_table("thread", sa.Column("id", sa.String(length=26), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_thread_id"), "thread", ["id"], unique=False)
    op.create_table(
        "tombstone",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("URI", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tombstone_URI"), "tombstone", ["URI"], unique=True)
    op.create_index(op.f("ix_tombstone_domain"), "tombstone", ["domain"], unique=False)
    op.create_index(op.f("ix_tombstone_id"), "tombstone", ["id"], unique=False)
    op.create_table(
        "actor",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("fetched", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "Application",
                "Group",
                "Organization",
                "Person",
                "Service",
                "Tombstone",
                name="actortype",
                checkfirst=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "name_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"name\")", persisted=True),
            nullable=True,
        ),
        sa.Column("preferredUsername", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("inbox", sa.String(), nullable=True),
        sa.Column("outbox", sa.String(), nullable=True),
        sa.Column("sharedInbox", sa.String(), nullable=True),
        sa.Column("following", sa.String(), nullable=True),
        sa.Column("followers", sa.String(), nullable=True),
        sa.Column("featured", sa.String(), nullable=True),
        sa.Column("liked", sa.String(), nullable=True),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("URL", sa.String(), nullable=True),
        sa.Column("icon_id", sa.String(length=26), nullable=True),
        sa.Column("iconURL", sa.String(), nullable=True),
        sa.Column("standout_id", sa.String(length=26), nullable=True),
        sa.Column("standoutURL", sa.String(), nullable=True),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("attachment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("alsoKnownAs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("privateKey", sa.String(), nullable=True),
        sa.Column("publicKey", sa.String(), nullable=False),
        sa.Column("publicKeyURI", sa.String(), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=True),
        sa.Column("discoverable", sa.Boolean(), nullable=True),
        sa.Column("memorial", sa.Boolean(), nullable=True),
        sa.Column("memorialised", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sensitised", sa.DateTime(timezone=True), nullable=True),
        sa.Column("silenced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["icon_id"],
            ["mediaattachment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["standout_id"],
            ["mediaattachment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("URL"),
        sa.UniqueConstraint("featured"),
        sa.UniqueConstraint("followers"),
        sa.UniqueConstraint("following"),
        sa.UniqueConstraint("outbox"),
        sa.UniqueConstraint("preferredUsername", "domain"),
        sa.UniqueConstraint("privateKey"),
        sa.UniqueConstraint("publicKey"),
        sa.UniqueConstraint("publicKeyURI"),
    )
    op.create_index(op.f("ix_actor_URI"), "actor", ["URI"], unique=True)
    op.create_index(op.f("ix_actor_domain"), "actor", ["domain"], unique=False)
    op.create_index(op.f("ix_actor_id"), "actor", ["id"], unique=False)
    op.create_index("ix_actor_name_vector", "actor", ["name_vector"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_actor_preferredUsername"), "actor", ["preferredUsername"], unique=False)
    op.create_table(
        "domainallow",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("private_comment", sa.String(), nullable=True),
        sa.Column("obfuscate", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domainallow_domain"), "domainallow", ["domain"], unique=False)
    op.create_index(op.f("ix_domainallow_id"), "domainallow", ["id"], unique=False)
    op.create_table(
        "domainblock",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("private_comment", sa.String(), nullable=True),
        sa.Column("obfuscate", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domainblock_domain"), "domainblock", ["domain"], unique=False)
    op.create_index(op.f("ix_domainblock_id"), "domainblock", ["id"], unique=False)
    op.create_table(
        "emaildomainblock",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emaildomainblock_domain"), "emaildomainblock", ["domain"], unique=False)
    op.create_index(op.f("ix_emaildomainblock_id"), "emaildomainblock", ["id"], unique=False)
    op.create_table(
        "mediadescription",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("media_id", sa.String(length=26), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("language", LocaleType(), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["mediaattachment.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mediadescription_id"), "mediadescription", ["id"], unique=False)
    op.create_table(
        "ruletext",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("rule_id", sa.String(length=26), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("language", LocaleType(), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["rule.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ruletext_id"), "ruletext", ["id"], unique=False)
    op.create_table(
        "actor_tag",
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("actor_id", "tag_id"),
    )
    op.create_table(
        "actormute",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=False),
        sa.Column("notifications", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actormute_URI"), "actormute", ["URI"], unique=True)
    op.create_index(op.f("ix_actormute_id"), "actormute", ["id"], unique=False)
    op.create_table(
        "actorsettings",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column(
            "privacy",
            postgresql.ENUM(
                "Private",
                "Public",
                "Unlocked",
                "Followers",
                "Mutuals",
                "Direct",
                name="visibilitytype",
                checkfirst=True,
            ),
            nullable=False,
        ),
        sa.Column("sensitive", sa.Boolean(), nullable=True),
        sa.Column("hide_collections", sa.Boolean(), nullable=True),
        sa.Column("enable_rss", sa.Boolean(), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actorsettings_id"), "actorsettings", ["id"], unique=False)
    op.create_table(
        "actorsummary",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column(
            "summary_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"summary\")", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["actor.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_actor_summary_vector", "actorsummary", ["summary_vector"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_actorsummary_id"), "actorsummary", ["id"], unique=False)
    op.create_table(
        "actorsummaryraw",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("summary_raw", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["actor.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actorsummaryraw_id"), "actorsummaryraw", ["id"], unique=False)
    op.create_table(
        "block",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_block_URI"), "block", ["URI"], unique=True)
    op.create_index(op.f("ix_block_id"), "block", ["id"], unique=False)
    op.create_table(
        "domainallowtext",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("domainallow_id", sa.String(length=26), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("language", LocaleType(), nullable=True),
        sa.ForeignKeyConstraint(["domainallow_id"], ["domainallow.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domainallowtext_id"), "domainallowtext", ["id"], unique=False)
    op.create_table(
        "domainblocktext",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("domainblock_id", sa.String(length=26), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("language", LocaleType(), nullable=True),
        sa.ForeignKeyConstraint(["domainblock_id"], ["domainblock.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domainblocktext_id"), "domainblocktext", ["id"], unique=False)
    op.create_table(
        "follow",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=False),
        sa.Column("has_accepted", sa.Boolean(), nullable=False),
        sa.Column("show_reposts", sa.Boolean(), nullable=True),
        sa.Column("notify", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_follow_URI"), "follow", ["URI"], unique=True)
    op.create_index(op.f("ix_follow_id"), "follow", ["id"], unique=False)
    op.create_table(
        "follow_tag",
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("actor_id", "tag_id"),
    )
    op.create_table(
        "moderatoraction",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "category",
            postgresql.ENUM(
                "Actor",
                "Status",
                "Media",
                "Work",
                "Purchase",
                "Domain",
                name="moderationcategorytype",
                checkfirst=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "action",
            postgresql.ENUM(
                "Disable",
                "Reenable",
                "Silence",
                "Unsilence",
                "Suspend",
                "Unsuspend",
                "Expire",
                name="moderatoractiontype",
                checkfirst=True,
            ),
            nullable=True,
        ),
        sa.Column("moderator_id", sa.String(length=26), nullable=False),
        sa.Column("decision", sa.String(), nullable=True),
        sa.Column("send_email", sa.Boolean(), nullable=True),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("errors", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["creator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_moderatoraction_domain"), "moderatoraction", ["domain"], unique=False)
    op.create_index(op.f("ix_moderatoraction_id"), "moderatoraction", ["id"], unique=False)
    op.create_table(
        "report",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("submitter_id", sa.String(length=26), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("actioned", sa.DateTime(timezone=True), nullable=True),
        sa.Column("forwarded", sa.Boolean(), nullable=True),
        sa.Column("moderator_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["creator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_URI"), "report", ["URI"], unique=True)
    op.create_index(op.f("ix_report_id"), "report", ["id"], unique=False)
    op.create_table(
        "status",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("fetched", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local", sa.Boolean(), nullable=True),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("URL", sa.String(), nullable=True),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("is_markdown", sa.Boolean(), nullable=True),
        sa.Column("sensitive", sa.Boolean(), nullable=True),
        sa.Column(
            "visibility",
            postgresql.ENUM(
                "Private",
                "Public",
                "Unlocked",
                "Followers",
                "Mutuals",
                "Direct",
                name="visibilitytype",
                checkfirst=True,
            ),
            nullable=False,
        ),
        sa.Column("edited", sa.Boolean(), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("actorURI", sa.String(), nullable=True),
        sa.Column("reply_id", sa.String(length=26), nullable=True),
        sa.Column("inReplyToURI", sa.String(), nullable=True),
        sa.Column("replyURI", sa.String(), nullable=True),
        sa.Column("reply_actor_id", sa.String(length=26), nullable=True),
        sa.Column("reply_actor_URI", sa.String(), nullable=True),
        sa.Column("share_id", sa.String(length=26), nullable=True),
        sa.Column("sharesURI", sa.String(), nullable=True),
        sa.Column("share_actor_id", sa.String(length=26), nullable=True),
        sa.Column("share_actor_URI", sa.String(), nullable=True),
        sa.Column("thread_id", sa.String(length=26), nullable=True),
        sa.Column("threadURI", sa.String(), nullable=True),
        sa.Column("likesURI", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["share_actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["share_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reply_actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reply_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("URL"),
    )
    op.create_index(op.f("ix_status_URI"), "status", ["URI"], unique=True)
    op.create_index(op.f("ix_status_actorURI"), "status", ["actorURI"], unique=False)
    op.create_index(op.f("ix_status_id"), "status", ["id"], unique=False)
    op.create_table(
        "threadmute",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("thread_id", sa.String(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threadmute_id"), "threadmute", ["id"], unique=False)
    op.create_table(
        "bookmark",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookmark_id"), "bookmark", ["id"], unique=False)
    op.create_table(
        "like",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.Column("URI", sa.String(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("approvedURI", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_like_URI"), "like", ["URI"], unique=True)
    op.create_index(op.f("ix_like_id"), "like", ["id"], unique=False)
    op.create_table(
        "media_attachments_association_table",
        sa.Column("attachment_id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["mediaattachment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.PrimaryKeyConstraint("attachment_id", "status_id"),
    )
    op.create_table(
        "mention",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("target_id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["actor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mention_id"), "mention", ["id"], unique=False)
    op.create_table(
        "notification",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "Follow",
                "FollowRequest",
                "Mention",
                "Repost",
                "Like",
                "Poll",
                "Post",
                "AdminSignup",
                "PendingLike",
                "PendingReply",
                "PendingRepost",
                "AdminReport",
                "Update",
                name="notificationtype",
                checkfirst=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("origin_id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_id"],
            ["actor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_id"), "notification", ["id"], unique=False)
    op.create_table(
        "report_action_association_table",
        sa.Column("report_id", sa.String(length=26), nullable=False),
        sa.Column("action_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["moderatoraction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("report_id", "action_id"),
    )
    op.create_table(
        "report_rule_association_table",
        sa.Column("report_id", sa.String(length=26), nullable=False),
        sa.Column("rule_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rule.id"],
        ),
        sa.PrimaryKeyConstraint("report_id", "rule_id"),
    )
    op.create_table(
        "report_status_association_table",
        sa.Column("report_id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.PrimaryKeyConstraint("report_id", "status_id"),
    )
    op.create_table(
        "status_tag",
        sa.Column("status_id", sa.String(), nullable=False),
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("status_id", "tag_id"),
    )
    op.create_table(
        "statuscontent",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column(
            "content_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"content\")", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["status_id"], ["status.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_status_content_vector", "statuscontent", ["content_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_statuscontent_id"), "statuscontent", ["id"], unique=False)
    op.create_table(
        "statuscontentheader",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("content_header", sa.String(), nullable=True),
        sa.Column(
            "content_header_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"content_header\")", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["status_id"], ["status.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_status_content_header_vector",
        "statuscontentheader",
        ["content_header_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_statuscontentheader_id"), "statuscontentheader", ["id"], unique=False)
    op.create_table(
        "statuscontentheaderraw",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("content_header_raw", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["status_id"], ["status.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statuscontentheaderraw_id"), "statuscontentheaderraw", ["id"], unique=False)
    op.create_table(
        "statuscontentraw",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("status_id", sa.String(length=26), nullable=False),
        sa.Column("language", LocaleType(), nullable=True),
        sa.Column("content_raw", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["status_id"], ["status.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statuscontentraw_id"), "statuscontentraw", ["id"], unique=False)
    op.add_column("creator", sa.Column("language", LocaleType(), nullable=True))
    op.drop_column("creator", "locale")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creator", sa.Column("locale", sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column("creator", "language")
    op.drop_index(op.f("ix_statuscontentraw_id"), table_name="statuscontentraw")
    op.drop_table("statuscontentraw")
    op.drop_index(op.f("ix_statuscontentheaderraw_id"), table_name="statuscontentheaderraw")
    op.drop_table("statuscontentheaderraw")
    op.drop_index(op.f("ix_statuscontentheader_id"), table_name="statuscontentheader")
    op.drop_index("ix_status_content_header_vector", table_name="statuscontentheader", postgresql_using="gin")
    op.drop_table("statuscontentheader")
    op.drop_index(op.f("ix_statuscontent_id"), table_name="statuscontent")
    op.drop_index("ix_status_content_vector", table_name="statuscontent", postgresql_using="gin")
    op.drop_table("statuscontent")
    op.drop_table("status_tag")
    op.drop_table("report_status_association_table")
    op.drop_table("report_rule_association_table")
    op.drop_table("report_action_association_table")
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_mention_id"), table_name="mention")
    op.drop_table("mention")
    op.drop_table("media_attachments_association_table")
    op.drop_index(op.f("ix_like_id"), table_name="like")
    op.drop_index(op.f("ix_like_URI"), table_name="like")
    op.drop_table("like")
    op.drop_index(op.f("ix_bookmark_id"), table_name="bookmark")
    op.drop_table("bookmark")
    op.drop_index(op.f("ix_threadmute_id"), table_name="threadmute")
    op.drop_table("threadmute")
    op.drop_index(op.f("ix_status_id"), table_name="status")
    op.drop_index(op.f("ix_status_actorURI"), table_name="status")
    op.drop_index(op.f("ix_status_URI"), table_name="status")
    op.drop_table("status")
    op.drop_index(op.f("ix_report_id"), table_name="report")
    op.drop_index(op.f("ix_report_URI"), table_name="report")
    op.drop_table("report")
    op.drop_index(op.f("ix_moderatoraction_id"), table_name="moderatoraction")
    op.drop_index(op.f("ix_moderatoraction_domain"), table_name="moderatoraction")
    op.drop_table("moderatoraction")
    op.drop_table("follow_tag")
    op.drop_index(op.f("ix_follow_id"), table_name="follow")
    op.drop_index(op.f("ix_follow_URI"), table_name="follow")
    op.drop_table("follow")
    op.drop_index(op.f("ix_domainblocktext_id"), table_name="domainblocktext")
    op.drop_table("domainblocktext")
    op.drop_index(op.f("ix_domainallowtext_id"), table_name="domainallowtext")
    op.drop_table("domainallowtext")
    op.drop_index(op.f("ix_block_id"), table_name="block")
    op.drop_index(op.f("ix_block_URI"), table_name="block")
    op.drop_table("block")
    op.drop_index(op.f("ix_actorsummaryraw_id"), table_name="actorsummaryraw")
    op.drop_table("actorsummaryraw")
    op.drop_index(op.f("ix_actorsummary_id"), table_name="actorsummary")
    op.drop_index("ix_actor_summary_vector", table_name="actorsummary", postgresql_using="gin")
    op.drop_table("actorsummary")
    op.drop_index(op.f("ix_actorsettings_id"), table_name="actorsettings")
    op.drop_table("actorsettings")
    op.drop_index(op.f("ix_actormute_id"), table_name="actormute")
    op.drop_index(op.f("ix_actormute_URI"), table_name="actormute")
    op.drop_table("actormute")
    op.drop_table("actor_tag")
    op.drop_index(op.f("ix_ruletext_id"), table_name="ruletext")
    op.drop_table("ruletext")
    op.drop_index(op.f("ix_mediadescription_id"), table_name="mediadescription")
    op.drop_table("mediadescription")
    op.drop_index(op.f("ix_emaildomainblock_id"), table_name="emaildomainblock")
    op.drop_index(op.f("ix_emaildomainblock_domain"), table_name="emaildomainblock")
    op.drop_table("emaildomainblock")
    op.drop_index(op.f("ix_domainblock_id"), table_name="domainblock")
    op.drop_index(op.f("ix_domainblock_domain"), table_name="domainblock")
    op.drop_table("domainblock")
    op.drop_index(op.f("ix_domainallow_id"), table_name="domainallow")
    op.drop_index(op.f("ix_domainallow_domain"), table_name="domainallow")
    op.drop_table("domainallow")
    op.drop_index(op.f("ix_actor_preferredUsername"), table_name="actor")
    op.drop_index("ix_actor_name_vector", table_name="actor", postgresql_using="gin")
    op.drop_index(op.f("ix_actor_id"), table_name="actor")
    op.drop_index(op.f("ix_actor_domain"), table_name="actor")
    op.drop_index(op.f("ix_actor_URI"), table_name="actor")
    op.drop_table("actor")
    op.drop_index(op.f("ix_tombstone_id"), table_name="tombstone")
    op.drop_index(op.f("ix_tombstone_domain"), table_name="tombstone")
    op.drop_index(op.f("ix_tombstone_URI"), table_name="tombstone")
    op.drop_table("tombstone")
    op.drop_index(op.f("ix_thread_id"), table_name="thread")
    op.drop_table("thread")
    op.drop_index("ix_tag_name_vector", table_name="tag", postgresql_using="gin")
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_index(op.f("ix_tag_id"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_rule_id"), table_name="rule")
    op.drop_table("rule")
    op.drop_index(op.f("ix_move_targetURI"), table_name="move")
    op.drop_index(op.f("ix_move_originURI"), table_name="move")
    op.drop_index(op.f("ix_move_id"), table_name="move")
    op.drop_index(op.f("ix_move_URI"), table_name="move")
    op.drop_table("move")
    op.drop_index(op.f("ix_mediaattachment_id"), table_name="mediaattachment")
    op.drop_table("mediaattachment")
    # ### end Alembic commands ###
