"""Media to Actor relationships

Revision ID: e52c67f37b76
Revises: 598b46663ceb
Create Date: 2025-10-21 14:14:27.560756

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e52c67f37b76"
down_revision = "598b46663ceb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("actor_icon_id_fkey"), "actor", type_="foreignkey")
    op.drop_constraint(op.f("actor_standout_id_fkey"), "actor", type_="foreignkey")
    op.drop_column("actor", "standout_id")
    op.drop_column("actor", "icon_id")
    op.add_column("mediaattachment", sa.Column("actor_avatar_id", sa.String(length=26), nullable=True))
    op.add_column("mediaattachment", sa.Column("actor_standout_id", sa.String(length=26), nullable=True))
    op.create_foreign_key(None, "mediaattachment", "actor", ["actor_avatar_id"], ["id"])
    op.create_foreign_key(None, "mediaattachment", "actor", ["actor_standout_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mediaattachment", type_="foreignkey")
    op.drop_constraint(None, "mediaattachment", type_="foreignkey")
    op.drop_column("mediaattachment", "actor_standout_id")
    op.drop_column("mediaattachment", "actor_avatar_id")
    op.add_column("actor", sa.Column("icon_id", sa.VARCHAR(length=26), autoincrement=False, nullable=True))
    op.add_column("actor", sa.Column("standout_id", sa.VARCHAR(length=26), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("actor_standout_id_fkey"), "actor", "mediaattachment", ["standout_id"], ["id"])
    op.create_foreign_key(op.f("actor_icon_id_fkey"), "actor", "mediaattachment", ["icon_id"], ["id"])
    # ### end Alembic commands ###
